#!/bin/bash
# Bulk Issue Operations Script
# Generated by Amber Triage Workflow
#
# This script performs bulk operations on issues based on triage recommendations.
# It supports both GitHub and Jira backends.
#
# Usage:
#   ./bulk-operations.sh [--dry-run] [--backend github|jira] [--repo owner/repo]
#
# Environment Variables:
#   GITHUB_TOKEN - GitHub personal access token
#   JIRA_URL - Jira instance URL
#   JIRA_EMAIL - Jira user email
#   JIRA_API_TOKEN - Jira API token

set -euo pipefail

# Configuration
DRY_RUN=false
BACKEND="github"
REPO=""
OPERATIONS_FILE="operations.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --backend)
      BACKEND="$2"
      shift 2
      ;;
    --repo)
      REPO="$2"
      shift 2
      ;;
    --operations)
      OPERATIONS_FILE="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Validate backend
if [[ "$BACKEND" != "github" && "$BACKEND" != "jira" ]]; then
  echo -e "${RED}Error: Backend must be 'github' or 'jira'${NC}"
  exit 1
fi

# Validate operations file exists
if [[ ! -f "$OPERATIONS_FILE" ]]; then
  echo -e "${RED}Error: Operations file not found: $OPERATIONS_FILE${NC}"
  exit 1
fi

echo -e "${GREEN}=== Bulk Issue Operations ===${NC}"
echo "Backend: $BACKEND"
echo "Repository: $REPO"
echo "Dry Run: $DRY_RUN"
echo "Operations File: $OPERATIONS_FILE"
echo ""

# GitHub Backend
if [[ "$BACKEND" == "github" ]]; then
  if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    echo -e "${RED}Error: GITHUB_TOKEN environment variable not set${NC}"
    exit 1
  fi

  if [[ -z "$REPO" ]]; then
    echo -e "${RED}Error: --repo required for GitHub backend${NC}"
    exit 1
  fi

  # Read operations from JSON file
  operations=$(cat "$OPERATIONS_FILE")

  # Process each operation
  echo "$operations" | jq -c '.[]' | while read -r op; do
    issue=$(echo "$op" | jq -r '.issue')
    action=$(echo "$op" | jq -r '.action')
    params=$(echo "$op" | jq -r '.params // {}')

    echo -e "${YELLOW}Processing #$issue: $action${NC}"

    case "$action" in
      CLOSE)
        reason=$(echo "$params" | jq -r '.reason // "Closed during triage"')
        if [[ "$DRY_RUN" == "false" ]]; then
          gh issue close "$issue" --repo "$REPO" --comment "$reason"
          echo -e "${GREEN}✓ Closed #$issue${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would close #$issue with comment: $reason${NC}"
        fi
        ;;

      ADD_LABEL)
        labels=$(echo "$params" | jq -r '.labels | join(",")')
        if [[ "$DRY_RUN" == "false" ]]; then
          gh issue edit "$issue" --repo "$REPO" --add-label "$labels"
          echo -e "${GREEN}✓ Added labels to #$issue: $labels${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would add labels to #$issue: $labels${NC}"
        fi
        ;;

      REMOVE_LABEL)
        labels=$(echo "$params" | jq -r '.labels | join(",")')
        if [[ "$DRY_RUN" == "false" ]]; then
          gh issue edit "$issue" --repo "$REPO" --remove-label "$labels"
          echo -e "${GREEN}✓ Removed labels from #$issue: $labels${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would remove labels from #$issue: $labels${NC}"
        fi
        ;;

      ASSIGN)
        assignee=$(echo "$params" | jq -r '.assignee')
        if [[ "$DRY_RUN" == "false" ]]; then
          gh issue edit "$issue" --repo "$REPO" --add-assignee "$assignee"
          echo -e "${GREEN}✓ Assigned #$issue to $assignee${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would assign #$issue to $assignee${NC}"
        fi
        ;;

      COMMENT)
        comment=$(echo "$params" | jq -r '.comment')
        if [[ "$DRY_RUN" == "false" ]]; then
          gh issue comment "$issue" --repo "$REPO" --body "$comment"
          echo -e "${GREEN}✓ Added comment to #$issue${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would comment on #$issue: $comment${NC}"
        fi
        ;;

      LINK_DUPLICATE)
        original=$(echo "$params" | jq -r '.original')
        if [[ "$DRY_RUN" == "false" ]]; then
          gh issue close "$issue" --repo "$REPO" --comment "Duplicate of #$original"
          echo -e "${GREEN}✓ Closed #$issue as duplicate of #$original${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would close #$issue as duplicate of #$original${NC}"
        fi
        ;;

      *)
        echo -e "${RED}Unknown action: $action${NC}"
        ;;
    esac

    # Rate limiting
    sleep 0.5
  done

# Jira Backend
elif [[ "$BACKEND" == "jira" ]]; then
  if [[ -z "${JIRA_URL:-}" || -z "${JIRA_EMAIL:-}" || -z "${JIRA_API_TOKEN:-}" ]]; then
    echo -e "${RED}Error: JIRA_URL, JIRA_EMAIL, and JIRA_API_TOKEN environment variables required${NC}"
    exit 1
  fi

  # Read operations from JSON file
  operations=$(cat "$OPERATIONS_FILE")

  # Process each operation
  echo "$operations" | jq -c '.[]' | while read -r op; do
    issue=$(echo "$op" | jq -r '.issue')
    action=$(echo "$op" | jq -r '.action')
    params=$(echo "$op" | jq -r '.params // {}')

    echo -e "${YELLOW}Processing $issue: $action${NC}"

    case "$action" in
      CLOSE)
        reason=$(echo "$params" | jq -r '.reason // "Closed during triage"')
        if [[ "$DRY_RUN" == "false" ]]; then
          curl -s -X POST \
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$JIRA_URL/rest/api/3/issue/$issue/transitions" \
            -d "{\"transition\": {\"id\": \"2\"}, \"fields\": {\"resolution\": {\"name\": \"Done\"}}}"

          curl -s -X POST \
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$JIRA_URL/rest/api/3/issue/$issue/comment" \
            -d "{\"body\": \"$reason\"}"

          echo -e "${GREEN}✓ Closed $issue${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would close $issue with comment: $reason${NC}"
        fi
        ;;

      ADD_LABEL)
        labels=$(echo "$params" | jq -r '.labels')
        if [[ "$DRY_RUN" == "false" ]]; then
          curl -s -X PUT \
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$JIRA_URL/rest/api/3/issue/$issue" \
            -d "{\"update\": {\"labels\": [{\"add\": $labels}]}}"

          echo -e "${GREEN}✓ Added labels to $issue${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would add labels to $issue: $labels${NC}"
        fi
        ;;

      ASSIGN)
        assignee=$(echo "$params" | jq -r '.assignee')
        if [[ "$DRY_RUN" == "false" ]]; then
          curl -s -X PUT \
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$JIRA_URL/rest/api/3/issue/$issue/assignee" \
            -d "{\"accountId\": \"$assignee\"}"

          echo -e "${GREEN}✓ Assigned $issue to $assignee${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would assign $issue to $assignee${NC}"
        fi
        ;;

      COMMENT)
        comment=$(echo "$params" | jq -r '.comment')
        if [[ "$DRY_RUN" == "false" ]]; then
          curl -s -X POST \
            -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            "$JIRA_URL/rest/api/3/issue/$issue/comment" \
            -d "{\"body\": \"$comment\"}"

          echo -e "${GREEN}✓ Added comment to $issue${NC}"
        else
          echo -e "${YELLOW}[DRY RUN] Would comment on $issue: $comment${NC}"
        fi
        ;;

      *)
        echo -e "${RED}Unknown action: $action${NC}"
        ;;
    esac

    # Rate limiting
    sleep 0.5
  done
fi

echo ""
echo -e "${GREEN}=== Operations Complete ===${NC}"

if [[ "$DRY_RUN" == "true" ]]; then
  echo -e "${YELLOW}This was a dry run. No changes were made.${NC}"
  echo "Remove --dry-run to execute operations."
fi
